### ISSUE TITLE
Freelance Cockpit 4.0.3

### ISSUE THREAD

**Issue by mv-stns** [octfx/FreelanceCockpitDocker#2]
Hi ich bin es nochmal,

kannst du mir einmal deinen raw code von deiner yml datei zeigen?

ich versteh nicht ganz was du meinst mit db settings

**Comment by octfx** [comment]
Na klar:
```yml
version: '3.5'

services:
  freelance-cockpit:
    image: freelance-cockpit
    container_name: freelance-cockpit
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      - db
    links:
      - db
    volumes:
      - /srv/freelance-cockpit:/var/www/html
      - /etc/freelance-cockpit/environment:/var/www/html/.env
      - /etc/localtime:/etc/localtime:ro	  
    ports:
      - 127.0.0.1:10080:80

  db:
    image: mariadb:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/lib/freelance-cockpit/db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro	  
    environment:
      - MYSQL_ROOT_PASSWORD=******
      - MYSQL_DATABASE=fc
      - MYSQL_USER=fc
      - MYSQL_PASSWORD=******
```

Der Step `Update MYSQL_ settings` soll heißen, dass in der `docker-compose.yml` Werte für die Datenbank, den User und das Passwort eingetragen werden müssen. Diese Werte kommen dann auch in die `environment` Datei und werden im Installationsprozess von FC gebraucht.
